name: Alerta Climatico Diario
on:
  schedule:
    - cron: '30 09 * * *' # Roda às 06:30 de Ibicoara (09:30 UTC)
  workflow_dispatch: # Permite que você teste manualmente agora

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar Script
        env:
          OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: python clima_alerta.py
