name: Alerta Climatico Diario
on:
  schedule:
    - cron: '30 09 * * *' # Roda às 9:30 UTC (06:30 Horário de Brasília)
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Instalar dependências
        run: pip install requests
      - name: Executar Script
        env:
          OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
          PUSHBULLET_TOKEN: ${{ secrets.PUSHBULLET_TOKEN }}
        run: python clima_alerta.py
