name: Alerta Climatico Diario

on:
  schedule:
    # 09h UTC = 06h Bahia (Relat√≥rio)
    # 14h UTC = 11h Bahia (Vigil√¢ncia 1)
    # 18h UTC = 15h Bahia (Vigil√¢ncia 2)
    - cron: '0 9,14,18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do c√≥digo
      uses: actions/checkout@v3
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Instalar depend√™ncias
      run: pip install requests
    - name: Executar Script Agro-Intel
      env:
        OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      run: python clima_alerta.py
    - name: Salvar Hist√≥rico
      run: |
        git config --global user.name "AgroRobot-Ibicoara"
        git config --global user.email "agro-robot@github.com"
        git add input_atividades.txt caderno_de_campo_master.csv
        git commit -m "üìù Log de Vigil√¢ncia" || echo "Sem altera√ß√µes"
        git push
