name: Alerta Climatico Diario

on:
  schedule:
    - cron: '0 9 * * *' # 06:00 em Ibicoara
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do c√≥digo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar depend√™ncias
      run: |
        python -m pip install --upgrade pip
        pip install requests google-generativeai

    - name: Executar Script Agro-Intel
      env:
        OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
      run: python clima_alerta.py

    - name: Salvar Hist√≥rico (Commit e Push)
      run: |
        git config --global user.name "AgroRobot-Ibicoara"
        git config --global user.email "agro-robot@github.com"
        git add input_atividades.txt caderno_de_campo_master.csv
        git commit -m "üìù Registro IA + Clima" || echo "Sem altera√ß√µes"
        git push
