name: Monitoramento Agro-Intel

on:
  schedule:
    # O GitHub usa o horário UTC (Londres). 
    # 09:00 UTC = 06:00 Bahia (Relatório Matinal)
    # 14:00 UTC = 11:00 Bahia (Vigilância 1)
    # 18:00 UTC = 15:00 Bahia (Vigilância 2)
    - cron: '0 9,14,18 * * *'
  workflow_dispatch: # Isso permite que você aperte o botão "Run Workflow" para testar a qualquer hora

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Executar Script
      env:
        OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      run: python clima_alerta.py

    - name: Salvar Logs e Histórico
      run: |
        git config --global user.name "AgroRobot"
        git config --global user.email "bot@github.com"
        git add input_atividades.txt caderno_de_campo_master.csv
        git commit -m "Registro Automático Agro-Intel" || echo "Sem alterações"
        git push
