name: Monitoramento Agro-Intel Premium

on:
  schedule:
    - cron: '0 9,14,18 * * *' # 06h, 11h e 15h (Horário Bahia)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Instalar dependências
      run: pip install requests
    - name: Executar Script
      env:
        OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      run: python clima_alerta.py
    - name: Salvar Histórico e Memória
      run: |
        git config --global user.name "AgroRobot"
        git config --global user.email "bot@github.com"
        git add input_atividades.txt caderno_de_campo_master.csv memoria_chuva.txt
        git commit -m "Registro de Laudo e Memória Estratégica" || echo "Sem alterações"
        git push
